### ISSUE TITLE
supporting other minifiers

### ISSUE THREAD

**Issue by yomed** [lasso-js/lasso-minify-css#1]
If I wanted to add support for different minifiers (like https://github.com/jakubpawlowicz/clean-css), should I create another plugin, or extend this one? I ask mostly because this is considered a "core" plugin and has a pretty generic project name.

**Comment by patrick-steele-idem** [comment]
Yes, @yomed, you can use a different minifier very easily, but you will need to create your own plugin. In addition, you would want to set the `minifyCSS` property to `false` in your `config.json` file to ensure the default CSS minifier is not enabled (otherwise you would be doing double minification...which isn't really a problem other than being slower). Implementing a plugin is not difficult and I recommend looking at the source code for the default CSS minifier as a guide:
https://github.com/lasso-js/lasso-minify-css/blob/master/lasso-minify-css-plugin.js

Here's the relevant documentation:
https://github.com/lasso-js/lasso#custom-output-transforms

Please let me know if that answers your question and I will go ahead and close the issue. Otherwise, please let me know if you have additional questions.

Also, if you do create a plugin and would like to share it with others please publish it to `npm` (perhaps named `lasso-clean-css`?) and submit a PR to add it to the [main README.md for Lasso.js](https://github.com/lasso-js/lasso/blob/master/README.md) under the following section:
https://github.com/lasso-js/lasso/blob/master/README.md#available-plugins

I hope that answers your question.

**Comment by yomed** [comment]
Sounds good, I'll look into creating a separate plugin. Thanks!
